# GitHub Release configuration
changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: 🚀 Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - fix
        - bug
        - bugfix
    - title: 📚 Documentation
      labels:
        - documentation
        - docs
    - title: 🎨 Performance Improvements
      labels:
        - performance
        - optimization
    - title: 🔧 Maintenance
      labels:
        - chore
        - maintenance
        - dependencies
    - title: ⚠️ Breaking Changes
      labels:
        - breaking-change
        - breaking
    - title: Other Changes
      labels:
        - "*"