export enum TransformMethod {
  NONE = "NONE",
  NORMALIZE = "NORMALIZE",
  DIFFERENCE = "DIFFERENCE",
  NORMALIZE_DIFFERENCE = "NORMALIZE_DIFFERENCE",
  SUBTRACT_MA = "SUBTRACT_MA",
  WEIGHTED = "WEIGHTED"
}